x-common-variables: &common-env
  CELERY_BROKER_URL: redis://redis_cache:6379/1
  REDIS_URL: redis://redis_cache:6379/2
  IS_DOCKER: 1

x-common-depends: &common-depends
  - redis_cache

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    command: gunicorn -k uvicorn.workers.UvicornWorker --threads 10 app:app --bind 0.0.0.0:8090
    ports:
      - "8090:8090"
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - internal
      - minio_network
    depends_on: *common-depends
    environment:
      <<: *common-env

  celery_worker_steam:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_start worker --loglevel=info --concurrency=1 -Q steam
    volumes:
      - .:/app
    depends_on: *common-depends
    environment:
      <<: *common-env
    restart: unless-stopped
    networks:
      - internal
      - minio_network

  celery_worker_steam_img:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_start worker --loglevel=info --concurrency=5 -Q steam_img
    volumes:
      - .:/app
    depends_on: *common-depends
    environment:
      <<: *common-env
    restart: unless-stopped
    networks:
      - internal
      - minio_network

  celery_worker_default:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_start worker --loglevel=info --concurrency=5 -Q default
    volumes:
      - .:/app
    depends_on: *common-depends
    environment:
      <<: *common-env
    restart: unless-stopped
    networks:
      - internal
      - minio_network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A celery_start beat --loglevel=info --schedule=/app/beat-schedule
    volumes:
      - .:/app
      - ./beat-schedule:/app/beat-schedule
    depends_on: *common-depends
    environment: *common-env
    restart: unless-stopped
    networks:
      - internal
      - minio_network

  celery_flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_flower
    command: celery -A celery_start flower
    volumes:
      - .:/app
      - ./beat-schedule:/app/beat-schedule
    depends_on: *common-depends
    environment:
      <<: *common-env
    ports:
      - "5555:5555"
    restart: unless-stopped
    networks:
      - internal
      - minio_network

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    command: >
      redis-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - internal
      - minio_network

networks:
  internal:
    driver: bridge
  minio_network:
    external: true
