"""bucket

Revision ID: efbff32b1201
Revises: 
Create Date: 2025-09-14 11:43:04.756544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'efbff32b1201'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'), schema='steam')
    op.create_table('games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Text(), nullable=True),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('required_age', sa.Integer(), nullable=True),
                    sa.Column('is_free', sa.Boolean(), nullable=True),
                    sa.Column('detailed_description', sa.Text(), nullable=True),
                    sa.Column('about_the_game', sa.Text(), nullable=True),
                    sa.Column('short_description', sa.Text(), nullable=True),
                    sa.Column('fullgame_appid', sa.Integer(), nullable=True),
                    sa.Column('fullgame_name', sa.Text(), nullable=True),
                    sa.Column('supported_languages', sa.ARRAY(sa.String(length=64)), nullable=True),
                    sa.Column('header_image', sa.Text(), nullable=True),
                    sa.Column('capsule_image', sa.Text(), nullable=True),
                    sa.Column('capsule_imagev5', sa.Text(), nullable=True),
                    sa.Column('website', sa.Text(), nullable=True),
                    sa.Column('pc_requirements', sa.JSON(), nullable=True),
                    sa.Column('mac_requirements', sa.JSON(), nullable=True),
                    sa.Column('linux_requirements', sa.JSON(), nullable=True),
                    sa.Column('developers', sa.ARRAY(sa.String(length=64)), nullable=True),
                    sa.Column('publishers', sa.ARRAY(sa.String(length=64)), nullable=True),
                    sa.Column('platforms_windows', sa.Boolean(), nullable=True),
                    sa.Column('platforms_mac', sa.Boolean(), nullable=True),
                    sa.Column('platforms_linux', sa.Boolean(), nullable=True),
                    sa.Column('release_date', sa.Date(), nullable=True),
                    sa.Column('coming_soon', sa.Boolean(), nullable=True),
                    sa.Column('background', sa.Text(), nullable=True),
                    sa.Column('background_raw', sa.Text(), nullable=True),
                    sa.Column('ratings', sa.JSON(), nullable=True),
                    sa.Column('total_reviews', sa.Integer(), nullable=True),
                    sa.Column('total_reviews_positive', sa.Integer(), nullable=True),
                    sa.Column('total_reviews_negative', sa.Integer(), nullable=True),
                    sa.Column('reviews_score', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'), schema='steam')
    op.create_table('games_to_categories',
                    sa.Column('id_games', sa.Integer(), nullable=False),
                    sa.Column('id_categories', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id_games', 'id_categories'),
                    schema='steam'
                    )
    op.create_table('games_to_genres',
                    sa.Column('id_games', sa.Integer(), nullable=False),
                    sa.Column('id_genres', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id_games', 'id_genres'),
                    schema='steam'
                    )
    op.create_table('games_to_package',
                    sa.Column('id_games', sa.Integer(), nullable=False),
                    sa.Column('id_package', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id_games', 'id_package'),
                    schema='steam'
                    )
    op.create_table('genres',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='steam'
                    )
    op.create_table('package',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('title', sa.Text(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('selection_text', sa.Text(), nullable=True),
                    sa.Column('save_text', sa.Text(), nullable=True),
                    sa.Column('display_type', sa.Integer(), nullable=True),
                    sa.Column('is_recurring_subscription', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='steam'
                    )
    op.create_table('screenshots',
                    sa.Column('id_games', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('path_thumbnail', sa.Text(), nullable=False),
                    sa.Column('path_full', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id_games', 'id'),
                    schema='steam'
                    )
    op.create_table('user_games',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('id_games', sa.Integer(), nullable=False),
                    sa.Column('playtime_hours', sa.BigInteger(), nullable=False),
                    sa.Column('rtime_last_played', sa.BigInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'id_games'),
                    schema='steam'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_games', schema='steam')
    op.drop_table('screenshots', schema='steam')
    op.drop_table('package', schema='steam')
    op.drop_table('genres', schema='steam')
    op.drop_table('games_to_package', schema='steam')
    op.drop_table('games_to_genres', schema='steam')
    op.drop_table('games_to_categories', schema='steam')
    op.drop_table('games', schema='steam')
    op.drop_table('categories', schema='steam')
    # ### end Alembic commands ###
